Repository codesquad-member-2020/dust-6, pull requests merged in 2020-04, with the labels that each got.

#19 [FE] 기본 마크업, 스타일링 작업 완료
  FE/.gitignore
  FE/config/webpack.config.dev.js
  FE/package.json
  FE/src/index.html
  FE/src/js/main.js
  FE/src/scss/config/_variables.scss
  FE/src/scss/config/reset.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/dust.scss
  FE/src/scss/pages/forecast.scss
  FE/src/scss/partials/header.scss
  FE/src/scss/styles.scss
Labels: FE

#18 데이터 모델, 그래프 스크롤 변화에 맞춘 상태화면 변화 구현
  iOS/Dust/Dust.xcodeproj/project.pbxproj
  iOS/Dust/Dust/Base.lproj/Main.storyboard
  iOS/Dust/Dust/DustDensityDataSource.swift
  iOS/Dust/Dust/DustDensityTableViewDelegate.swift
  iOS/Dust/Dust/Extension/CAGradientLayerExtension.swift
  iOS/Dust/Dust/FineDustViewController.swift
  iOS/Dust/Dust/GraphTableViewDelegate.swift
  iOS/Dust/Dust/Model/DataManager.swift
  iOS/Dust/Dust/Model/DustStatus.swift
  iOS/Dust/Dust/View/DensityLabel.swift
  iOS/Dust/Dust/View/DustDensityCell.swift
  iOS/Dust/Dust/View/DustDensityDataSource.swift
  iOS/Dust/Dust/View/DustDensityTableView.swift
  iOS/Dust/Dust/View/MeasurementTimeLabel.swift
  iOS/Dust/Dust/View/StationLabel.swift
  iOS/Dust/Dust/View/StatusEmoji.swift
  iOS/Dust/Dust/View/StatusLabel.swift
  iOS/Dust/Dust/View/StatusView.swift
Labels: iOS

#25 [FE] skeleton 코드 작성 및 테스트 완료
  FE/config/webpack.config.dev.js
  FE/src/js/controllers/DustController.js
  FE/src/js/controllers/ForecastController.js
  FE/src/js/main.js
  FE/src/js/models/DustModel.js
  FE/src/js/models/ForecastModel.js
  FE/src/js/utils/Observable.js
  FE/src/js/utils/mockData.js
  FE/src/js/views/DustView.js
  FE/src/js/views/ForecastView.js
Labels: FE

#26 [FE] 화면 전환 기능 추가
  FE/src/js/controllers/NavController.js
  FE/src/js/controllers/SwipeController.js
  FE/src/js/main.js
Labels: FE

#28 [FE] 화면 레이아웃 및 스타일 업데이트 완료
  FE/src/index.html
  FE/src/scss/config/_variables.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/dust.scss
  FE/src/scss/pages/forecast.scss
  FE/src/scss/partials/header.scss
Labels: FE

#30 [FE] 미세먼지 화면 데이터 요청 기능 추가
  FE/src/index.html
  FE/src/js/controllers/DustController.js
  FE/src/js/models/DustModel.js
  FE/src/js/utils/http.js
  FE/src/scss/main.scss
Labels: FE

#31 [FE] webpack build 환경 구축
  FE/config/webpack.config.prod.js
  FE/package.json
Labels: FE

#33 GPS 를 활용해 현재 위치 좌표 가져오기 구현
  iOS/Dust/Dust.xcodeproj/project.pbxproj
  iOS/Dust/Dust/FineDustViewController.swift
  iOS/Dust/Dust/Info.plist
  iOS/Dust/Dust/LocationManagerDelegate.swift
Labels: iOS

#35 서버와 통신해 데이터 받아와 화면에 업데이트 구현
  iOS/Dust/Dust.xcodeproj/project.pbxproj
  iOS/Dust/Dust/Base.lproj/Main.storyboard
  iOS/Dust/Dust/FineDustViewController.swift
  iOS/Dust/Dust/Info.plist
  iOS/Dust/Dust/LocationManagerDelegate.swift
  iOS/Dust/Dust/Model/DataManager.swift
  iOS/Dust/Dust/Model/DustStatus.swift
  iOS/Dust/Dust/Model/NetworkManager.swift
  iOS/Dust/Dust/View/DensityLabel.swift
  iOS/Dust/Dust/View/MeasurementTimeLabel.swift
  iOS/Dust/Dust/View/StationLabel.swift
  iOS/Dust/Dust/View/StatusEmoji.swift
  iOS/Dust/Dust/View/StatusLabel.swift
  iOS/Dust/Dust/View/StatusView.swift
Labels: iOS

#38 [FE] 모바일 디바이스에서 레이아웃 틀어짐 이슈 해결 Close #37
  FE/src/index.html
  FE/src/scss/config/_variables.scss
  FE/src/scss/main.scss
  FE/src/scss/pages/dust.scss
  FE/src/scss/pages/forecast.scss
  FE/src/scss/partials/header.scss
Labels: FE

#41 [FE] 미세먼지 화면 렌더링 기능 구현
  FE/src/index.html
  FE/src/js/main.js
  FE/src/js/models/DustModel.js
  FE/src/js/views/DustView.js
  FE/src/js/views/template.js
  FE/src/scss/pages/dust.scss
Labels: FE

#43 [BE] 미세먼지 예보 기능 구현
  BE/src/main/java/com/codesquad/dust6/api/ApiDustStatusController.java
  BE/src/main/java/com/codesquad/dust6/api/ApiForecastController.java
  BE/src/main/java/com/codesquad/dust6/domain/ForecastDTO.java
  BE/src/main/java/com/codesquad/dust6/service/LocationService.java
  BE/src/main/java/com/codesquad/dust6/utils/JsonUtils.java
  BE/src/main/java/com/codesquad/dust6/utils/KakaoUtils.java
  BE/src/main/java/com/codesquad/dust6/utils/PublicInstitutionUtils.java
Labels: BE

#44 [FE] 미세먼지 화면 인터랙션 구현
  FE/package.json
  FE/src/js/controllers/DustController.js
  FE/src/js/models/DustModel.js
  FE/src/js/utils/Observable.js
  FE/src/js/utils/const.js
  FE/src/js/utils/utilFunction.js
  FE/src/js/views/DustView.js
  FE/src/js/views/template.js
  FE/src/scss/pages/dust.scss
Labels: FE

#45 예보 화면 UI 구현
  iOS/Dust/Dust.xcodeproj/project.pbxproj
  iOS/Dust/Dust.xcodeproj/xcshareddata/xcschemes/Dust.xcscheme
  iOS/Dust/Dust/Assets.xcassets/forecast.imageset/Contents.json
  iOS/Dust/Dust/Assets.xcassets/forecast.imageset/forecast.png
  iOS/Dust/Dust/Base.lproj/Main.storyboard
  iOS/Dust/Dust/View/PlayButton.swift
Labels: iOS

#50 [FE] 예보 화면 렌더링 기능 구현
  FE/src/index.html
  FE/src/js/models/ForecastModel.js
  FE/src/js/views/ForecastView.js
  FE/src/js/views/template.js
Labels: FE

#53 [FE] 미세먼지 화면 geoLocation 응답 대기 기능 추가
  FE/src/js/controllers/DustController.js
  FE/src/js/models/DustModel.js
  FE/src/js/utils/const.js
Labels: FE

#54 [BE] cors 오류 수정을 위한 WebConfig 파일 생성
  BE/src/main/java/com/codesquad/dust6/utils/WebConfig.java
Labels: BE

#55 [FE] 예보 화면 데이터 요청 기능 추가
  FE/src/index.html
  FE/src/js/models/DustModel.js
  FE/src/js/models/ForecastModel.js
  FE/src/js/utils/const.js
  FE/src/scss/main.scss
Labels: FE

#56 예보정보를 서버에서 받아와 뷰 업데이트
  iOS/Dust/Dust.xcodeproj/project.pbxproj
  iOS/Dust/Dust/Base.lproj/Main.storyboard
  iOS/Dust/Dust/FineDustViewController.swift
  iOS/Dust/Dust/ForecastViewController.swift
  iOS/Dust/Dust/Info.plist
  iOS/Dust/Dust/Model/DataManager.swift
  iOS/Dust/Dust/Model/Forecast.swift
  iOS/Dust/Dust/Model/ForecastDataManager.swift
  iOS/Dust/Dust/Model/NetworkManager.swift
Labels: iOS

#60 [FE] 이벤트리스너가 바인딩되지 않는 이슈 해결
  FE/src/js/controllers/DustController.js
  FE/src/js/controllers/ForecastController.js
  FE/src/js/main.js
  FE/src/js/models/DustModel.js
  FE/src/js/views/DustView.js
Labels: FE

#64 [FE] 예보화면 애니메이션 구현
  FE/src/js/utils/const.js
  FE/src/js/views/ForecastView.js
  FE/src/js/views/template.js
  FE/src/scss/pages/forecast.scss
Labels: FE

#66 [BE] 오전 12시 - 5시 예보 대체
  BE/src/main/java/com/codesquad/dust6/api/ApiForecastController.java
Labels: BE
